metadata:
  name: "bert"
  description: "A BERT (Binary ERlang Term) serialization library for Ruby. It can encode Ruby objects into BERT format and decode BERT binaries into Ruby objects."
  labels:
    stack: 
      - "ruby"
      - "c"
    product: "dsp"
    jira-project: "SDSP"
    jira-board: 182
    public: "false"
  links:
    - url: https://adgear.atlassian.net/l/cp/9kD8ZGRe
      title: "confluence page"

spec:
  owner: "cg-dsp-api"
  type: "library"
  lifecycle: "production"
